<?php

/**
 * @file
 * d8dw Paragraphs module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use \Drupal\file\Entity\File;
use Drupal\file\FileInterface;
use Drupal\image\Entity\ImageStyle;
use Drupal\Core\Render\Element;
use Drupal\paragraphs\Entity\Paragraph;



function d8dw_contenttype_product_uninstall() {
  $files = [
    'core.entity_form_display.node.produkt_bier.default',
    'core.entity_view_display.node.produkt_bier.default',
    'core.entity_view_display.node.produkt_bier.teaser',

    'field.field.node.produkt_bier.field_prod_backimg_1',
    'field.field.node.produkt_bier.field_prod_backimg_2',
    'field.field.node.produkt_bier.field_prod_backimg_3',
    'field.field.node.produkt_bier.field_prod_beschreibung',
    'field.field.node.produkt_bier.field_prod_beschreibung_mobil',
    'field.field.node.produkt_bier.field_prod_bild_1',
    'field.field.node.produkt_bier.field_prod_bild_2',
    'field.field.node.produkt_bier.field_prod_bild_3',
    'field.field.node.produkt_bier.field_prod_bild_4',
    'field.field.node.produkt_bier.field_prod_eigenschaft_1',
    'field.field.node.produkt_bier.field_prod_eigenschaft_1_beschr',
    'field.field.node.produkt_bier.field_prod_eigenschaft_1_wertung',
    'field.field.node.produkt_bier.field_prod_eigenschaft_2',
    'field.field.node.produkt_bier.field_prod_eigenschaft_2_beschr',
    'field.field.node.produkt_bier.field_prod_eigenschaft_2_wertung',
    'field.field.node.produkt_bier.field_prod_eigenschaft_3',
    'field.field.node.produkt_bier.field_prod_eigenschaft_3_beschr',
    'field.field.node.produkt_bier.field_prod_eigenschaft_3_wertung',
    'field.field.node.produkt_bier.field_prod_eigenschaft_4',
    'field.field.node.produkt_bier.field_prod_eigenschaft_4_beschr',
    'field.field.node.produkt_bier.field_prod_eigenschaft_4_wertung',
    'field.field.node.produkt_bier.field_prod_eigenschaft_5',
    'field.field.node.produkt_bier.field_prod_eigenschaft_5_beschr',
    'field.field.node.produkt_bier.field_prod_eigenschaft_5_wertung',
    'field.field.node.produkt_bier.field_prod_laenderzuordnung',
    'field.field.node.produkt_bier.field_prod_merkmal_1',
    'field.field.node.produkt_bier.field_prod_merkmal_1_text',
    'field.field.node.produkt_bier.field_prod_merkmal_2',
    'field.field.node.produkt_bier.field_prod_merkmal_2_text',
    'field.field.node.produkt_bier.field_prod_merkmal_3',
    'field.field.node.produkt_bier.field_prod_merkmal_3_text',
    'field.field.node.produkt_bier.field_prod_merkmal_4',
    'field.field.node.produkt_bier.field_prod_merkmal_4_text',
    'field.field.node.produkt_bier.field_prod_naehrwert',

    'field.storage.node.field_prod_backimg_1',
    'field.storage.node.field_prod_backimg_2',
    'field.storage.node.field_prod_backimg_3',
    'field.storage.node.field_prod_beschreibung',
    'field.storage.node.field_prod_beschreibung_mobil',
    'field.storage.node.field_prod_bild_1',
    'field.storage.node.field_prod_bild_2',
    'field.storage.node.field_prod_bild_3',
    'field.storage.node.field_prod_bild_4',
    'field.storage.node.field_prod_eigenschaft_1',
    'field.storage.node.field_prod_eigenschaft_1_beschr',
    'field.storage.node.field_prod_eigenschaft_1_wertung',
    'field.storage.node.field_prod_eigenschaft_2',
    'field.storage.node.field_prod_eigenschaft_2_beschr',
    'field.storage.node.field_prod_eigenschaft_2_wertung',
    'field.storage.node.field_prod_eigenschaft_3',
    'field.storage.node.field_prod_eigenschaft_3_beschr',
    'field.storage.node.field_prod_eigenschaft_3_wertung',
    'field.storage.node.field_prod_eigenschaft_4',
    'field.storage.node.field_prod_eigenschaft_4_beschr',
    'field.storage.node.field_prod_eigenschaft_4_wertung',
    'field.storage.node.field_prod_eigenschaft_5',
    'field.storage.node.field_prod_eigenschaft_5_beschr',
    'field.storage.node.field_prod_eigenschaft_5_wertung',
    'field.storage.node.field_prod_laenderzuordnung',
    'field.storage.node.field_prod_merkmal_1',
    'field.storage.node.field_prod_merkmal_1_text',
    'field.storage.node.field_prod_merkmal_2',
    'field.storage.node.field_prod_merkmal_2_text',
    'field.storage.node.field_prod_merkmal_3',
    'field.storage.node.field_prod_merkmal_3_text',
    'field.storage.node.field_prod_merkmal_4',
    'field.storage.node.field_prod_merkmal_4_text',
    'field.storage.node.field_prod_naehrwert',
    'language.content_settings.node.produkt_bier',

    'node.type.produkt_bier',
  ];

  foreach ($files as $file) {
    \Drupal::configFactory()->getEditable($file)->delete();
  }
}